digitalnatives/course_planner

- mix.exs
- mix.lock
- priv/repo/migrations/20170413165808_full_user.exs
- priv/repo/seeds.exs
- priv/static/js/app.js
- test/controllers/user_controller_test.exs
- web/controllers/coherence/redirects.ex
- web/controllers/user_controller.ex
- web/models/coherence/user.ex
- web/router.ex
- web/templates/coherence/invitation/new.html.eex
- web/templates/page/index.html.eex
- web/templates/user/edit.html.eex
- web/templates/user/form.html.eex
- web/templates/user/index.html.eex
- web/templates/user/show.html.eex
- web/views/user_view.ex
User crud view with `send_invite` instead of `create`.
Pending [this PR](https://github.com/smpallen99/coherence/pull/182) in [coherence](https://github.com/smpallen99/coherence/) project.
> User crud view

- .dockerignore
- .gitignore
- Dockerfile
- README.md
- config/dev.exs
- config/test.exs
- docker-compose.yml
- docker-compose.yml.sample
- scripts/docker-compose-up.sh.sample
Add docker setup to easy development onboarding
> Add docker setup

- lib/user_role.ex
- priv/repo/migrations/20170424080542_create_role.exs
- web/models/coherence/user.ex
- web/templates/user/form.html.eex
Add user role through the create user form.
> Add user role.

- test/controllers/student_controller_test.exs
- web/controllers/student_controller.ex
- web/router.ex
- web/templates/student/index.html.eex
- web/views/student_view.ex
I created a separate controller/view/template for the students to not clump the user controller too much and to separate the permissions as well when it comes to placing it, but I'm not too sure about it.
Thoughts @ggpasqualino @ghatighorias ?
> List all students

- lib/course_planner/types/participation_type.ex
- priv/repo/migrations/20170426145752_add_student_status_and_type.exs
- priv/static/js/app.js
- test/controllers/student_controller_test.exs
- web/controllers/student_controller.ex
- web/models/coherence/user.ex
- web/models/students.ex
- web/router.ex
- web/templates/student/edit.html.eex
- web/templates/student/form.html.eex
- web/templates/student/index.html.eex
- web/templates/student/show.html.eex
> Edit students

- lib/course_planner/coordinators.ex
- lib/course_planner/teachers.ex
- lib/course_planner/users.ex
- test/controllers/coordinator_controller_test.exs
- web/controllers/coordinator_controller.ex
- web/controllers/student_controller.ex
- web/controllers/teacher_controller.ex
- web/models/coherence/user.ex
- web/router.ex
- web/templates/coordinator/edit.html.eex
- web/templates/coordinator/form.html.eex
- web/templates/coordinator/index.html.eex
- web/templates/coordinator/show.html.eex
- web/views/coordinator_view.ex
List, show and edit coordinator.
There's a few modifications from other branches that is polluting the PR, so I'll leave it here until it is merged and update it.
Does is sound good or should I wait until merged to create the PR, @ggpasqualino ?
> Manage coordinator

- lib/course_planner/users.ex
- lib/course_planner/volunteers.ex
- test/controllers/user_controller_test.exs
- test/controllers/volunteer_controller_test.exs
- web/controllers/volunteer_controller.ex
- web/router.ex
- web/templates/teacher/index.html.eex
- web/templates/volunteer/edit.html.eex
- web/templates/volunteer/form.html.eex
- web/templates/volunteer/index.html.eex
- web/templates/volunteer/new.html.eex
- web/templates/volunteer/show.html.eex
- web/views/volunteer_view.ex
List, show, edit, create and delete volunteer.
> Manage volunteer

- lib/course_planner/coordinators.ex
- lib/course_planner/teachers.ex
- lib/course_planner/users.ex
- test/controllers/coordinator_controller_test.exs
- test/controllers/student_controller_test.exs
- test/controllers/teacher_controller_test.exs
- test/controllers/user_controller_test.exs
- web/controllers/coordinator_controller.ex
- web/controllers/student_controller.ex
- web/controllers/teacher_controller.ex
- web/controllers/user_controller.ex
- web/models/students.ex
- web/router.ex
- web/templates/coordinator/index.html.eex
- web/templates/coordinator/new.html.eex
- web/templates/student/form.html.eex
- web/templates/student/index.html.eex
- web/templates/student/new.html.eex
- web/templates/teacher/index.html.eex
- web/templates/teacher/new.html.eex
- web/templates/user/index.html.eex
Create separate new and delete actions for the roles.
> Create specific views for roles

- .travis.yml
- lib/course_planner/enum.ex
- web/models/students.ex
Fix existing warnings in the compilation and add warning-as-errors in the ci script
> Warnings as errors

- priv/static/js/app.js
- web/models/terms.ex
- web/models/terms/term.ex
- web/static/js/app.js
- web/templates/term/form.html.eex
- web/templates/term/holiday_fields.html.eex
- web/views/term_view.ex
* Add dynamic fields for holidays, add/remove fields on the fly
* Add empty list for holidays if there is no holidays parameter when
updating a term
* Replace the whole holidays json when saving
> Add Term's holidays nested fields

- priv/repo/migrations/20170511074507_create_offered_course.exs
- test/controllers/term_controller_test.exs
- test/models/offered_course_test.exs
- web/controllers/term_controller.ex
- web/models/course/course.ex
- web/models/offered_course.ex
- web/models/terms.ex
- web/models/terms/term.ex
- web/templates/term/form.html.eex
- web/templates/term/show.html.eex
- web/views/term_view.ex
- Add OfferedCourse, the association between Term and Course
- Show the courses of a term in the Term show page
- Add/remove courses of term in the Term new/edit pages
> Assign courses to terms

- priv/repo/migrations/20170512120635_create_offered_courses_students.exs
- test/controllers/offered_course_controller_test.exs
- web/controllers/offered_course_controller.ex
- web/models/offered_course.ex
- web/models/students.ex
- web/router.ex
- web/templates/offered_course/edit.html.eex
- web/templates/offered_course/form.html.eex
- web/templates/offered_course/index.html.eex
- web/templates/offered_course/new.html.eex
- web/templates/offered_course/show.html.eex
- web/views/offered_course_view.ex
- Add CRUD to offered courses (course in a given term)
- Add students to offered courses
> Assign students to courses

- test/controllers/page_controller_test.exs
- web/router.ex
- web/templates/layout/app.html.eex
- web/templates/page/index.html.eex
- Add basic navigation bar
- Move index page to protected pipeline
> Add basic navigation bar

- lib/course_planner/tasks.ex
- priv/repo/migrations/20170504190323_create_tasks.exs
- priv/repo/seeds.exs
- test/controllers/task_controller_test.exs
- test/lib/course_planner/tasks_test.exs
- test/models/task_test.exs
- web/controllers/task_controller.ex
- web/models/tasks/task.ex
- web/router.ex
- web/templates/task/index_volunteer.html.eex
Volunteer view for tasks to grab and mark as done.
> Volunteer view for tasks

- .travis.yml
https://dockyard.com/blog/2015/12/02/speeding-up-elixir-project-build-times-on-travis-ci
> Add cache to travis build to make it faster

- priv/static/js/app.js
- web/static/js/app.js
The hidden_id node is only present for persisted holidays, so we need to check if we can find it before removing
> Remove hidden_id node only if it is present

- config/config.exs
- lib/course_planner/permissions.ex
- mix.exs
- mix.lock
- test/controllers/task_controller_test.exs
- test/lib/course_planner/permissions_test.exs
- test/lib/course_planner/tasks_test.exs
- web/controllers/task_controller.ex
- web/helper.ex
- web/views/error_view.ex
- Setup user permission with canada and canary
- Restrict volunteers' permission
> Restrict user permission

- test/models/term_test.exs
- web/models/terms/term.ex
Validate if start_date is before end_date.
The code looks a bit clunky and I couldn't figure out a better way of doing it, so I'm asking for some feedback @ggpasqualino @ghatighorias .
> Validate start_date before end_date.

- lib/course_planner/permissions.ex
- test/controllers/term_controller_test.exs
- test/lib/course_planner/permissions_test.exs
- web/controllers/term_controller.ex
Students, Teachers, and Volunteers can't do anything with Terms
> Add restriction to Term

- priv/repo/migrations/20170607082525_add_offered_course_unique_index.exs
- test/controllers/offered_course_controller_test.exs
- web/models/offered_course.ex
* With this validation each course can be offered only once in each term.
> Fixes bug that allowed a course be offered multiple times in a term

- priv/repo/migrations/20170612082135_migrate_fields_from_course_to_offered_course.exs
- test/controllers/course_controller_test.exs
- test/controllers/offered_course_controller_test.exs
- test/lib/course_planner/offered_courses_test.exs
- test/models/class_test.exs
- test/models/course_test.exs
- test/models/offered_course_test.exs
- test/support/factory.ex
- web/models/course/course.ex
- web/models/offered_course.ex
- web/templates/course/form.html.eex
- web/templates/course/index.html.eex
- web/templates/course/show.html.eex
- web/templates/offered_course/form.html.eex
- web/templates/offered_course/index.html.eex
- web/templates/offered_course/show.html.eex
removes "session_duration" from courses
moves "syllabus" and "number_of_sessions" to offered_courses
> Move fields from course to offered_course

- web/models/class/class.ex
- web/templates/class/form.html.eex
this change was requested by Laci to be aligned with thee frontend design
> Renames offered_course_status as error_tag to offered_course_id

- web/static/css/layout.scss
- web/templates/layout/app.html.eex
- web/views/attendance_view.ex
- web/views/class_view.ex
- web/views/coordinator_view.ex
- web/views/course_view.ex
- web/views/offered_course_view.ex
- web/views/student_view.ex
- web/views/task_view.ex
- web/views/teacher_view.ex
- web/views/term_view.ex
- web/views/user_view.ex
- web/views/volunteer_view.ex
- web/web.ex
* Added page_title functions to views
* Added backlink to layout
* Added title to layout that uses page_title function if it presents
> Added page title & backlink to layout

- config/test.exs
- lib/course_planner/users.ex
- test/controllers/coordinator_controller_test.exs
- test/controllers/student_controller_test.exs
- test/controllers/teacher_controller_test.exs
- test/controllers/user_controller_test.exs
- test/controllers/volunteer_controller_test.exs
- test/lib/course_planner/offered_courses_test.exs
- test/lib/course_planner/teachers_test.exs
- test/models/students_test.exs
- test/models/task_test.exs
- test/support/factory.ex
- web/models/coherence/user.ex
- web/models/students.ex
* Always call coherence validation in User changesets
* Fix the tests setup
> Add coherence validation for User changesets

- web/templates/class/form.html.eex
- web/templates/shared/form_date.html.eex
- web/templates/shared/form_datetime.html.eex
- web/templates/shared/form_time.html.eex
- web/templates/task/form.html.eex
- web/views/shared_view.ex
Description in the following nostromo card
https://app.nostromo.io/work/course-planner/fix-the-default-time-for-task-class-and-term-form?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjkzMzc1LGNhcmRfdGl0bGU6Zml4LXRoZS1kZWZhdWx0LXRpbWUtZm9yLXRhc2stY2xhc3MtYW5kLXRlcm0tZm9ybX0=
> Sets default date and, time for task, class and term form

- lib/course_planner/offered_courses.ex
- lib/course_planner/permissions.ex
- test/controllers/offered_course_controller_test.exs
- test/lib/course_planner/offered_courses_test.exs
- web/controllers/offered_course_controller.ex
* Add index to the allowed actions of OfferedCourseController for
Teachers and Students
* Filter OfferedCourses returned in the index action according to
the current_user
> Allow Teachers and Students to access OfferedCourse index

- test/lib/course_planner/coherence_user_email_test.exs
- web/controllers/coordinator_controller.ex
- web/controllers/student_controller.ex
- web/controllers/teacher_controller.ex
- web/controllers/volunteer_controller.ex
- web/emails/coherence/user_email.ex
- web/templates/coherence/email/welcome.html.eex
Before when we created a new user we sent them a reset password email,
but that's confusing user experience, so we will send a welcome email
with the link to set the password
> Send welcome email

- lib/course_planner/permissions.ex
- test/lib/course_planner/permissions_test.exs
- web/controllers/calendar_controller.ex
- web/controllers/class_controller.ex
- web/controllers/course_controller.ex
- web/controllers/course_matrix_controller.ex
- web/controllers/dashboard_controller.ex
- web/controllers/page_controller.ex
- web/controllers/task_controller.ex
- web/controllers/term_controller.ex
* Reorder permissions
* Use controller authorization where possible
> Clean up permissions

- web/templates/class/form.html.eex
- web/templates/shared/form_date.html.eex
- web/templates/shared/form_datetime.html.eex
- web/templates/shared/form_time.html.eex
- web/templates/task/form.html.eex
- web/views/shared_view.ex
The bug is because I put the default value to priority and do not check for the changed value of changeset.
> Fixes bug that caused edit always shows the default time and date

- priv/repo/migrations/20170801141406_change_system_variable_value_to_text_adds_required.exs
- test/models/system_variable_test.exs
- test/support/factory.ex
- web/models/setting/system_variable.ex
1. adds required field, and custom validation
2. makes the value field text for not be limited to 255 characters
3. introduce validation for string and url
> Adds new types to system variables

- lib/course_planner/notifications.ex
Run wake_up notifications when it was run one or more days ago
>  wake_up notification period

- lib/course_planner/offered_courses.ex
- lib/course_planner_web/models/summary_helper.ex
- test/lib/course_planner/offered_courses_test.exs
this PR introduces the functionality to find offered_courses with correctly preloaded classes which have not filled attendance
> Introduces functionality with test

- lib/course_planner_web/models/setting/system_variable.ex
- test/lib/course_planner/settings_test.exs
this modification is making frontend part more neat
> returns nil when url type setting is empty string

- README.md
- app.json
- config/prod.exs
Add Heroku Manifest in order to have a "Deploy to Heroku" button.
It would be nicer to get the logo from somewhere else instead of the staging server because that might be sleeping.
> deploy to heroku button

- lib/course_planner_web/templates/coherence/layout/app.html.eex
It was not possible to open the `Forgot your password?` and the reset
password link from the email because we were trying to render always
from the SessionView.
> Use the assigned view

- lib/course_planner/accounts/coordinators.ex
- lib/course_planner/accounts/students.ex
- lib/course_planner/accounts/teachers.ex
- lib/course_planner/accounts/user.ex
- lib/course_planner/accounts/users.ex
- lib/course_planner/accounts/volunteers.ex
- test/lib/course_planner/accounts/user_test.exs
Currently role is not explicitly required in the user changeset. and it should be added
> Adds role to user changeset validation

- priv/repo/seeds.exs
check the comments under this card
https://app.nostromo.io/work/course-planner/settings-page-ui?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjkyNTg1LGNhcmRfdGl0bGU6c2V0dGluZ3MtcGFnZS11aX0=
> adds PROGRAM_EMAIL to setting show page

- lib/course_planner/accounts/users.ex
- lib/course_planner_web/controllers/coordinator_controller.ex
- test/controllers/coordinator_controller_test.exs
description : https://app.nostromo.io/work/course-planner/self-deletion-can-cause-the-app-unstable?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjk2MzAwLGNhcmRfdGl0bGU6c2VsZi1kZWxldGlvbi1jYW4tY2F1c2UtdGhlLWFwcC11bnN0YWJsZX0=
> restricts self deletion for coordinators

- lib/course_planner_web/templates/attendance/show_coordinator.html.eex
- lib/course_planner_web/templates/attendance/show_student.html.eex
- lib/course_planner_web/templates/offered_course/show.html.eex
- lib/course_planner_web/templates/shared/user_bubble.html.eex
- lib/course_planner_web/templates/shared/user_list.html.eex
- lib/course_planner_web/templates/task/show.html.eex
- lib/course_planner_web/views/shared_view.ex
description : https://app.nostromo.io/work/course-planner/students-and-teachers-redirects-to-403-when-clicking-on-classmate-or-teachers-profile?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjk2Mjk5LGNhcmRfdGl0bGU6c3R1ZGVudHMtYW5kLXRlYWNoZXJzLXJlZGlyZWN0cy10by00MDMtd2hlbi1jbGlja2luZy1vbi1jbGFzc21hdGUtb3ItdGVhY2hlcnMtcHJvZmlsZX0=
> restrict the user list to be clickable only for coordinators

- lib/course_planner_web/controllers/user_controller.ex
- test/controllers/user_controller_test.exs
description : https://app.nostromo.io/work/course-planner/password-reset-link-error?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjk2Mzg2LGNhcmRfdGl0bGU6cGFzc3dvcmQtcmVzZXQtbGluay1lcnJvcn0=
> Fixes the resend of reset password link error

- mix.exs
- mix.lock
Check session_controller.ex line 81
And yes, for this very line i had to regenerate all the coherence controllers
> Makes login case insensitive

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Code of Conduct
- Contribution Guideline
- Pull Request Template
- Issue Template
> Guidelines

- assets/css/app.scss
- lib/course_planner/courses/offered_courses.ex
- lib/course_planner_web/templates/course_matrix/index.html.eex
- lib/course_planner_web/views/course_matrix_view.ex
- test/lib/course_planner/courses/offered_courses_test.exs
- test/views/course_matrix_test.exs
1 - adds horizental scrolling when the list goes off screen
2 - adds tooltip with the list of common students for classes that have at least 1 student in common
> adds tooltip and horizontal scrolling to course conflict matrix

- lib/course_planner/attendances/attendances.ex
consider class starting time for ordering as well
it is important since there might be two classes for one offered_course on the same day
> considers class starting time for ordering as well

- assets/css/app.scss
- assets/css/term-list.scss
- lib/course_planner/terms/terms.ex
- lib/course_planner_web/controllers/student_controller.ex
- lib/course_planner_web/templates/student/show.html.eex
This PR give the student show page an overview of her attendance to all classes grouped by terms
> Adds student attendances to show page

- mix.exs
- mix.lock
updates in tag v0.5.2 :
1. downcasing password reset and unlocking email as well.
2. trimming email address for logging, password reset and unlocking
> updates coherence to tag v0.5.2

- lib/course_planner_web/templates/event/index.html.eex
- lib/course_planner_web/templates/layout/coordinator_app_navbar.html.eex
- lib/course_planner_web/templates/layout/student_app_navbar.html.eex
- lib/course_planner_web/templates/layout/teacher_app_navbar.html.eex
- lib/course_planner_web/templates/layout/volunteer_app_navbar.html.eex
- Put events in the sidebar
- Hide new/edit/delete buttons for non-coordinators
> Fix event pages

- lib/course_planner_web/controllers/auth/api_session_controller.ex
- lib/course_planner_web/router.ex
- test/controllers/json_session_controller_test.exs
> logging in through json

- lib/course_planner/accounts/coordinators.ex
- lib/course_planner/accounts/students.ex
- lib/course_planner/accounts/teachers.ex
- lib/course_planner/accounts/users.ex
- lib/course_planner/accounts/volunteers.ex
- lib/course_planner/attendances/attendances.ex
- lib/course_planner/classes/classes.ex
- lib/course_planner/courses/courses.ex
- lib/course_planner/events/events.ex
- lib/course_planner/tasks/tasks.ex
- lib/course_planner/terms/terms.ex
- lib/course_planner_web/controllers/class_controller.ex
- lib/course_planner_web/controllers/course_controller.ex
- lib/course_planner_web/controllers/term_controller.ex
Sorting is the following for index pages.
For user related controllers (student, teacher, volunteer, coordinator and user controllers)
- Sorting is ascending based on Name, family_name and nickname
For Entities with Date or time (task, event, attendance, class, offered_course, term)
- Sorting is descending based on the following order [date, start time, finishing time]
For Course since it only has a name
- Sorting is ascending based on its name
> Adds proper sorting for all index pages

- mix.exs
Adds a mix task for the development to go smoother
it will check compilation warning, dogma and credo --strict
> Adds mix task to check format and warning

- assets/css/calendar.scss
- assets/js/calendar.js
1 - uses promises to read both class and event api
2 - convert the results to a common structure
3 - refactor calendar and breaks it in two function 
---1. render the whole calendar
---2. render days and slots in place
4 - generate the common slots for both events and classes and render them together
5 - Renames the switch at the bottom of the calendar to "display every slot"
> Shows the events to the calendar

- lib/course_planner/events/events.ex
- lib/course_planner_web/controllers/event_controller.ex
- lib/course_planner_web/templates/event/index.html.eex
- lib/course_planner_web/templates/event/index_event.html.eex
- test/course_planner/events/events_test.exs
- test/course_planner_web/controllers/event_controller_test.exs
Also, fix event sorting:
- was only considering `starting_time` and `finishing_time` since the `date` part is separated
- was `desc` instead of `asc`
> Split event in index by past and future.

- assets/css/calendar.scss
- assets/js/calendar.js
Provides day view for the calendar
> Provides the day view option
