digitalnatives/course_planner

priv/repo/migrations/20170418123613_fix_user.exs, priv/repo/seeds.exs, test/controllers/user_controller_test.exs, web/models/coherence/user.ex, web/templates/user/form.html.eex, web/templates/user/index.html.eex, web/templates/user/show.html.eex
Upon building the user view with `send invitation` instead of a new user, I made the mistake of renaming the `name` field as `first_name`, breaking the reset password functionality, maybe more stuff I didn't test or need.
Now since we kind of require `family_name`, I'll leave the fields `name, family_name` for now until we figure out how to customize the field being filled by the forms.
=> Fix password reset

lib/course_planner/statuses.ex, priv/repo/migrations/20170424120050_rename_terms_status_timestamps.exs, test/lib/course_planner/statuses_test.exs, web/models/terms/term.ex
Refactor `CoursePlanner.Statuses.update_status_timestamp/1` to calculate
the possible timestamp field names from the enum type
`CoursePlanner.Types.EntityStatus`
=> Calculate status timestamp field name

lib/course_planner/enum.ex, lib/course_planner/statuses.ex, lib/course_planner/student_status.ex, lib/enum_timestamp.ex, priv/repo/migrations/20170503181307_rename_user_status.exs, priv/repo/migrations/20170504140508_change_timestamp_type.exs, test/lib/course_planner/statuses_test.exs, web/models/coherence/user.ex, web/models/students.ex, web/models/terms/term.ex, web/models/types/entity_status.ex
Define a behaviour to help using Enum types easier, with an optional helper with the timestamp.
As you can see in `EntityStatus`, it's cleaner to define an Enum to be used. The schema type could still be an `EntityStatus` but a subset could be passed to restrict the choosable types (see `CoursePlanner.Students` and `CoursePlanner.StudentStatus`).
=> Generalize Enum type

Dockerfile, docker-compose.yml.sample, scripts/docker-compose-up.sh.sample
The watchers could not work with the symlinks, so they are removed.
The dependencies and compilation are removed from the image because they
can't be reused.
Now it uses the current workdir for deps, build and node_modules.
=> Fix asset reloading in docker

web/views/term_view.ex
When editing a term with holidays fails the validation the value for
`Form.input_value(form, field)` is a map instead of a list
=> Fix link to add holiday

test/controllers/term_controller_test.exs, web/models/offered_course.ex, web/models/terms.ex, web/templates/term/form.html.eex, web/templates/term/show.html.eex, web/views/term_view.ex
Remove course manipulation from terms as we discussed since `OfferedCourse` already provides the needed functionality.
=> Remove course manipulation from term scope

lib/course_planner/mailer/user_email.ex, lib/course_planner/notifier.ex, lib/course_planner/users.ex, test/lib/course_planner/user_email_test.exs, web/controllers/class_controller.ex, web/controllers/coordinator_controller.ex, web/controllers/course_controller.ex, web/controllers/student_controller.ex, web/controllers/teacher_controller.ex, web/controllers/term_controller.ex, web/controllers/user_controller.ex, web/controllers/volunteer_controller.ex, web/models/class/class_helper.ex, web/models/course/course_helper.ex, web/models/terms.ex, web/templates/email/class_updated.html.eex, web/templates/email/course_updated.html.eex, web/templates/email/term_updated.html.eex, web/templates/email/user_updated.html.eex
To build the resource link in the template, we would need `Plug.Conn` passed around which I thought it was bad idea, so I'm sending the path through a parameter.
It might be getting a little bit clunky with too many parameters, but I couldn't think of a better way, so please take a look @ggpasqualino @ghatighorias if you have a better idea.
=> Send resource link in e-mail notifications

web/controllers/class_controller.ex, web/controllers/coordinator_controller.ex, web/controllers/course_controller.ex, web/controllers/student_controller.ex, web/controllers/teacher_controller.ex, web/controllers/term_controller.ex, web/controllers/user_controller.ex, web/controllers/volunteer_controller.ex
Before we were sending notifications with broken links because they had
only the path of the resource instead of the full url.
=> Replace resource path by url

test/controllers/attendance_controller_test.exs, web/controllers/attendance_controller.ex, web/models/attendance/attendance_helper.ex
* preloads the teacher and students and does not show them in index if there none attached to offered_course
* fixes controller if query fails to find all data for display ( students and teachers and attendances of a class) then show return 404
[related nostromo card](https://app.nostromo.io/work/course-planner/internal-server-error-showing-an-attendance?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjkxMDIwLGNhcmRfdGl0bGU6aW50ZXJuYWwtc2VydmVyLWVycm9yLXNob3dpbmctYW4tYXR0ZW5kYW5jZX0=)
=> Fixes Error in show attendance when no student or teacher for class

lib/course_planner/permissions.ex, test/controllers/coordinator_controller_test.exs, test/controllers/student_controller_test.exs, test/controllers/teacher_controller_test.exs, test/controllers/user_controller_test.exs, test/controllers/volunteer_controller_test.exs, web/controllers/coordinator_controller.ex, web/controllers/student_controller.ex, web/controllers/teacher_controller.ex, web/controllers/user_controller.ex, web/controllers/volunteer_controller.ex
Restrict user access to `{student, teacher, coordinator, volunteer and user}_controller`s apart from showing, editing and updating himself.
=> Restrict user permission to user controllers.

web/emails/coherence/user_email.ex
Our user has name and family name so we won't split it to send the
email, instead we send with the name.
The user may not have a name, in that case the email should be the email
without name
=> Change user name and email on coherence mailer

test/controllers/class_controller_test.exs, test/controllers/course_controller_test.exs, test/controllers/dashboard_controller_test.exs, test/controllers/task_controller_test.exs, web/static/css/card.scss, web/static/css/layout.scss, web/templates/layout/app.html.eex, web/templates/user/form.html.eex
* Added profile dropdown to the navigation bar
* Removed student related fields (they are accessible from the student
form)
* Adedd profile-picture, with gravatar link
* Added phone number, so Coordinators, Teachers, and Volunteers can edit
their own
* Added condition to role selector, so only Coordinators can change it
=> Modified user form to can be used as edit profile form too

web/views/shared_view.ex
The error message may contain variable to be replaced, for example
"should be at most %{count} character(s)"
=> Use translated error message instead of raw error 

test/controllers/setting_controller_test.exs, web/controllers/setting_controller.ex, web/models/setting/settings.ex, web/router.ex, web/templates/setting/show.html.eex
1. Separates the system_variables to system and program and uses two different tables to list them in the show page
2. introduces two separate edit link for editing system and program related system variables separately
3. updates the router so edit can get an id to select editing between system or program system_variables
4. updates the current tests and introduces new ones
=> Introduces categorized show and edit for system variables

test/controllers/class_controller_test.exs, test/models/class_test.exs, test/models/summary_helper_test.exs, test/support/factory.ex, web/models/summary_helper.ex
1. Makes term_factory and affected test independent from hardcoded date
2. Adds functionality for retriving terms and offered_course for users
3. adds a function to get the next_class
Note : the function for getting volunteer tasks is not in this pull request, it will be added after max_volunter pull request gets closed
=> creates summary page helpers

lib/course_planner/notifications.ex
This is necessary in order to use the update changeset
=> Make the `NOTIFICATION_JOB_EXECUTED_AT` variable editable

lib/course_planner_web/models/setting/settings.ex, priv/repo/seeds.exs
Settings.get_value function should return nil in case the value saved for the setting is nil so it can use the default value
this is especially important  for url type setting with empty string. we have already save it as nil and now we should consider get_value returning the default value in case system_variable.value is equal to nil
=> bug fix : no function clause matching in String.Chars.URI.to_string/1

Procfile, app.json, compile
Set MIX_ENV in Heroku and let the mix commands use the value set in the
environment.
This allows the deploy commands to be used with other environments like
Gigalixir.
=> Remove fixed MIX_ENV=prod

lib/course_planner/notifications/notifications.ex, lib/course_planner/settings/settings.ex, lib/course_planner/settings/system_variable.ex, lib/course_planner_web/controllers/setting_controller.ex, priv/repo/seeds.exs, test/lib/course_planner/settings/system_variable_test.exs
Currently "NOTIFICATION_JOB_EXECUTED_AT" is shown on the edit page and with this PR it will be removed from the edit page
=> Remove "NOTIFICATION_JOB_EXECUTED_AT" from the edit page

lib/course_planner_web/controllers/bulk_controller.ex, test/controllers/bulk_controller_test.exs
Before we always got an error that the file was not given because the
parameters were not matching.
=> Match file upload to Plug.Upload structure

lib/course_planner/notifications/notification.ex, lib/course_planner_web/templates/email/attendance_missing.html.eex, lib/course_planner_web/templates/email/summary.html.eex, test/lib/course_planner/mailer/user_email_test.exs, test/lib/course_planner/notifications/server_test.exs
- Add `attendance_missing` to allowed notification type
- Add notification data to the email summary rendering
- Change access of json notification data from atom to string
=> Fix Attendance missing notification

lib/course_planner/accounts/teachers.ex, lib/course_planner/courses/offered_courses.ex, lib/course_planner_web/controllers/offered_course_controller.ex, lib/course_planner_web/templates/offered_course/index.html.eex, lib/course_planner_web/templates/offered_course/teacher_edit.html.eex, lib/course_planner_web/templates/offered_course/teacher_edit_form.html.eex, test/controllers/offered_course_controller_test.exs
1 - add edit button to offered_courses index page for teacher
2 - teacher can render only edit page for offered_courses assigned to her
3 - teacher can update only Syllabus of offered courses assigned to her
detail : https://app.nostromo.io/work/course-planner/teacher-can-edit-the-course-by-modifying-the-link?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjk2Mjg3LGNhcmRfdGl0bGU6dGVhY2hlci1jYW4tZWRpdC10aGUtY291cnNlLWJ5LW1vZGlmeWluZy10aGUtbGlua30=
=> Introduced restriction on edit and update for teacher

lib/course_planner_web/templates/about/show.html.eex, lib/course_planner_web/templates/offered_course/show.html.eex, lib/course_planner_web/templates/student/show.html.eex, lib/course_planner_web/templates/task/show.html.eex, lib/course_planner_web/views/shared_view.ex
description : https://app.nostromo.io/work/course-planner/text-stylings-like-newline-is-ignored-in-text-and-string-fields?e21vZHVsZTp3b3JrLHByb2plY3Q6NjM2OCxjYXJkOjk2NDYzLGNhcmRfdGl0bGU6dGV4dC1zdHlsaW5ncy1saWtlLW5ld2xpbmUtaXMtaWdub3JlZC1pbi10ZXh0LWFuZC1zdHJpbmctZmllbGRzfQ==
=> show newline in description and comment fields

lib/course_planner/classes/classes.ex, lib/course_planner_web/controllers/class_controller.ex, lib/course_planner_web/templates/class/index.html.eex
1 - create different sections for classes based on terms and offered courses
2 - sort classes with the following order : term date, class date, class starting time and class finishing time
Ideally the same needs to be done for the offered_courses index page and attendance index page
with the difference that they just need to be separate based on Terms. but they can be done in a separate PR
=> Organizes class index page

lib/course_planner/attendances/attendances.ex, lib/course_planner_web/templates/attendance/fill_course_attendance.html.eex, lib/course_planner_web/templates/attendance/show_coordinator.html.eex, lib/course_planner_web/views/attendance_view.ex
ordering was forgotten to be added for the teacher and was just added for the coordinator. this commit ensures the ordering based on the student name and family_name to be added for the teacher as well
root cause :
in the show we use "get_teacher_course_attendances" while in fill we use "get_course_attendances" function to retrive all the attendances. both have to have the same sorting order so the rendered order of the students and attendance be the same
The same problem won't happen for student cause he only sees his own attendance and need no sorting on name or family_name
=> Fixes wrong attendance order

lib/course_planner/accounts/user.ex, test/course_planner_web/controllers/user_controller_test.exs
password limit of 8 character was just being checked on password reset page and not on user update page ( it was wrongly still on 6 characters )
=> Fixes password length check when user updates itself
